name: distr_test

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "**.md"
      - "benches/**"
      - "examples/**"
  pull_request:
    branches: [ master ]
    paths-ignore:
      - "**.md"
      - "benches/**"
      - "examples/**"

defaults:
  run:
    working-directory: ./distr_test

jobs:
  clippy-fmt:
    name: "distr_test: Check Clippy and rustfmt"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: Rustfmt
        run: cargo fmt -- --check
      - name: Clippy
        run: cargo clippy --workspace -- -D warnings
  ks-tests:
    name: "distr_test: Run Komogorov Smirnov tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - run: cargo test --release
